### ISSUE TITLE
似乎回答后面都会出现一个“undefined”

### ISSUE THREAD

**Issue by codejiangqihan** [anhao/duckduckgo-ai#2]
看起来似乎每个回答后面都有，应该是Duckduckgo的接口的问题，直接去除最后面的undefined应该就可以（但应该有更好的办法）

**Comment by anhao** [comment]
已更新 https://github.com/anhao/duckduckgo-ai/commit/c14d9490bf1c1699833375de8c76c9f5ce57638e
